name: powerpc/allconfig

# Controls when the action will run.
on:
  # This allows the build to be triggered manually via the github UI.
  workflow_dispatch:

  push:
    # This triggers the build on a push to merge-test only
    branches:
    - '**'

jobs:
  kernel:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # ppc64le allmod and allyes
          - subarch: ppc64le
            defconfig: ppc64le_allmodconfig
            image: fedora-40
          - subarch: ppc64le
            defconfig: allyesconfig
            image: fedora-40
            merge_config: /linux/arch/powerpc/configs/le.config
          # ppc64 allmod and allyes
          - subarch: ppc64
            defconfig: allmodconfig
            image: fedora-40
          - subarch: ppc64
            defconfig: allyesconfig
            image: fedora-40
          # ppc32 allmod
          - subarch: ppc
            defconfig: ppc32_allmodconfig
            image: fedora-40
          # ppc64 book3e allmod
          # Broken due to head_check.sh
          #- subarch: ppc64
          #  defconfig: ppc64_book3e_allmodconfig
          #  image: fedora-40

    env:
      ARCH: powerpc
      TARGET: kernel
      CCACHE: 1
      SUBARCH: ${{ matrix.subarch }}
      IMAGE: ${{ matrix.image }}
      DEFCONFIG: ${{ matrix.defconfig }}
      MERGE_CONFIG: /linux/arch/powerpc/configs/disable-werror.config,${{ matrix.merge_config }}

    steps:
    - uses: actions/checkout@v4

    - name: Register problem matchers
      run: |
        echo "::add-matcher::.github/problem-matchers/compiler-source.json"
        echo "::add-matcher::.github/problem-matchers/compiler-non-source.json"

    - name: Load ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ matrix.image }}-${{ matrix.subarch }}-${{ matrix.defconfig }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        mkdir -p ~/.ccache
        ./arch/powerpc/tools/ci-build.sh
